name: quast
channels:
  - anaconda
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.0=anacondar_1
  - about-time=4.2.1=pyhd8ed1ab_1
  - alive-progress=3.0.1=pyhd8ed1ab_0
  - alsa-lib=1.2.11=hd590300_1
  - aragorn=1.2.41=h7b50bb2_5
  - archspec=0.2.5=pyhd8ed1ab_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - bakta=1.8.1=pyhdfd78af_0
  - barrnap=0.9=hdfd78af_4
  - bbmap=39.09=h92535d8_0
  - bedtools=2.31.1=hf5e1c6e_2
  - binutils_impl_linux-64=2.40=h5293946_0
  - bio_assembly_refinement=0.5.1=py_2
  - biom-format=2.1.16=py312h66e93f0_2
  - biopython=1.85=py312h66e93f0_1
  - blas=1.0=openblas
  - blast=2.16.0=h66d330f_5
  - blosc=1.21.6=he440d0b_1
  - bottleneck=1.3.7=py312ha883a20_0
  - bowtie2=2.5.4=h7071971_4
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotli-python=1.1.0=py312h2ec8cdc_2
  - bwa=0.7.18=he4a0461_1
  - bwidget=1.9.16=h9eba36c_0
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.32.3=h4bc722e_0
  - c-blosc2=2.17.1=h3122c55_0
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.0=h3faef2a_0
  - capnproto=1.1.0=hfc315d8_0
  - certifi=2025.6.15=py312h06a4308_0
  - cffi=1.17.1=py312h06ac9bb_0
  - cgecore=1.5.6=pyh3252c3a_0
  - charset-normalizer=3.4.2=pyhd8ed1ab_0
  - circlator=1.5.5=py_2
  - circos=0.69.9=hdfd78af_0
  - click=8.1.8=pyh707e725_0
  - comm=0.2.1=py312h06a4308_0
  - contourpy=1.3.0=py312h68727a3_1
  - curl=8.8.0=he654da7_1
  - cycler=0.12.1=pyhd8ed1ab_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - dfast=1.3.6=h5ca1c30_0
  - diamond=2.1.10=h43eeafb_2
  - entrez-direct=22.4=he881be0_0
  - et_xmlfile=1.1.0=py312h06a4308_1
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.3=h5888daf_0
  - fastqc=0.12.1=hdfd78af_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_2
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.53.1=py312h66e93f0_1
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h7b6447c_0
  - gcc_impl_linux-64=11.2.0=h1234567_1
  - gettext=0.22.5=he02047a_3
  - gettext-tools=0.22.5=he02047a_3
  - gfortran_impl_linux-64=7.5.0=h56cb351_20
  - ghostx=1.3.7=h503566f_2
  - giflib=5.2.2=hd590300_0
  - glimmerhmm=3.0.4=pl5321hdbdd923_8
  - grapheme=0.6.0=pyhd8ed1ab_1
  - graphite2=1.3.13=h59595ed_1003
  - gsl=2.6=ha341630_0
  - gxx_impl_linux-64=11.2.0=h1234567_1
  - h2=4.2.0=pyhd8ed1ab_0
  - h5py=3.13.0=nompi_py312hedeef09_100
  - harfbuzz=8.5.0=hfac3d4d_0
  - hdf5=1.14.3=nompi_hdf9ad27_105
  - hmmer=3.4=h503566f_3
  - hpack=4.1.0=pyhd8ed1ab_0
  - htslib=1.21=h5efdd21_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.2=h59595ed_0
  - idna=3.10=pyhd8ed1ab_1
  - infernal=1.1.5=pl5321h7b50bb2_4
  - ipysankeywidget=0.5.0=pyhd8ed1ab_0
  - ipython=8.27.0=py312h06a4308_0
  - ipywidgets=8.1.2=py312h06a4308_0
  - isa-l=2.31.1=hb9d3cd8_1
  - jedi=0.19.1=py312h06a4308_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.10=py312h06a4308_0
  - k8=1.2=h6618dc6_3
  - kernel-headers_linux-64=3.10.0=he073ed8_18
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.7=py312h68727a3_0
  - kma=1.4.15=he4a0461_0
  - kraken-biom=1.2.0=pyh5e36f6f_0
  - kraken2=2.14=pl5321h077b44d_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h27087fc_0
  - libaec=1.1.3=h59595ed_0
  - libasprintf=0.22.5=he8f35ee_3
  - libasprintf-devel=0.22.5=he8f35ee_3
  - libblas=3.9.0=24_linux64_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcblas=3.9.0=24_linux64_openblas
  - libcups=2.3.3=h4637d8d_4
  - libcurl=8.8.0=hca28451_1
  - libdeflate=1.20=hd590300_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libexpat=2.6.3=h5888daf_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.1.0=h77fa898_1
  - libgcc-devel_linux-64=11.2.0=h1234567_1
  - libgcc-ng=14.1.0=h69a702a_1
  - libgd=2.3.3=h119a65a_9
  - libgettextpo=0.22.5=he02047a_3
  - libgettextpo-devel=0.22.5=he02047a_3
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgfortran5=14.1.0=hc5f4f2c_1
  - libglib=2.80.2=hf974151_0
  - libgomp=14.1.0=h77fa898_1
  - libiconv=1.17=hd590300_2
  - libidn2=2.3.7=hd590300_0
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=24_linux64_openblas
  - libnghttp2=1.58.0=h47da74e_1
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.27=pthreads_hac2b453_1
  - libpng=1.6.43=h2797004_0
  - libsqlite=3.49.2=hee588c1_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx=14.1.0=hc0a3c3a_1
  - libstdcxx-devel_linux-64=11.2.0=h1234567_1
  - libstdcxx-ng=14.1.0=h4852527_1
  - libtiff=4.6.0=h1dd3fc0_3
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.50.0=hb9d3cd8_0
  - libwebp=1.4.0=h2c329e2_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - lz4-c=1.10.0=h5888daf_1
  - lzo=2.10=h7b6447c_2
  - make=4.2.1=h1bed415_1
  - mash=1.1=0
  - matplotlib-base=3.9.2=py312hd3ec401_1
  - matplotlib-inline=0.1.6=py312h06a4308_0
  - metagene_annotator=1.0=h516909a_3
  - minimap2=2.28=he4a0461_3
  - mob_suite=1.4.9.1=py_0
  - mummer=3.23=pl5321h503566f_21
  - mummer4=4.0.0rc1=pl5321hdbdd923_7
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncbi-amrfinderplus=3.12.8=h283d18e_0
  - ncbi-vdb=3.2.1=h9948957_0
  - ncurses=6.5=he02047a_1
  - numexpr=2.8.7=py312he7dcb8a_0
  - numpy=1.26.4=py312h2809609_0
  - numpy-base=1.26.4=py312he1a6c75_0
  - openjdk=22.0.1=hb622114_0
  - openjpeg=2.5.2=h488ebb8_0
  - openpyxl=3.1.5=py312h5eee18b_1
  - openssl=3.5.0=h7b32b05_1
  - packaging=24.1=pyhd8ed1ab_0
  - pandas=2.2.2=py312h526ad5a_0
  - pango=1.54.0=h84a9a3c_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pbzip2=1.1.13=h1fcc475_2
  - pcre=8.45=h9c3ff4c_0
  - pcre2=10.43=hcad00b1_0
  - perl=5.32.1=7_hd590300_perl5
  - perl-archive-tar=2.40=pl5321hdfd78af_0
  - perl-b-cow=0.007=pl5321hd590300_0
  - perl-carp=1.50=pl5321hd8ed1ab_0
  - perl-clone=0.46=pl5321h166bdaf_0
  - perl-common-sense=3.75=pl5321hd8ed1ab_0
  - perl-compress-raw-bzip2=2.201=pl5321h166bdaf_0
  - perl-compress-raw-zlib=2.202=pl5321h166bdaf_0
  - perl-config-general=2.65=pl5321hdfd78af_0
  - perl-digest-perl-md5=1.9=pl5321hdfd78af_2
  - perl-encode=3.21=pl5321hd590300_0
  - perl-exporter=5.74=pl5321hd8ed1ab_0
  - perl-exporter-tiny=1.002002=pl5321hd8ed1ab_0
  - perl-extutils-config=0.008=pl5321ha770c72_0
  - perl-extutils-helpers=0.026=pl5321ha770c72_0
  - perl-extutils-installpaths=0.012=pl5321ha770c72_0
  - perl-extutils-makemaker=7.70=pl5321hd8ed1ab_0
  - perl-extutils-pl2bat=0.005=pl5321ha770c72_0
  - perl-font-ttf=1.06=pl5321hdfd78af_1
  - perl-gd=2.56=0
  - perl-inc-latest=0.500=pl5321ha770c72_0
  - perl-io-compress=2.201=pl5321hdbdd923_2
  - perl-io-string=1.08=pl5321hdfd78af_4
  - perl-io-zlib=1.14=pl5321hdfd78af_0
  - perl-json=4.10=pl5321hdfd78af_1
  - perl-json-xs=4.03=pl5321h4ac6f70_3
  - perl-list-moreutils=0.430=pl5321hdfd78af_0
  - perl-list-moreutils-xs=0.430=pl5321h031d066_2
  - perl-math-bezier=0.01=pl5321hdfd78af_2
  - perl-math-round=0.07=pl5321ha770c72_0
  - perl-math-vecstat=0.08=pl5321hdfd78af_2
  - perl-module-build=0.4232=pl5321ha770c72_0
  - perl-module-build-tiny=0.039=pl5321h166bdaf_0
  - perl-module-implementation=0.09=pl5321ha770c72_0
  - perl-module-runtime=0.016=pl5321ha770c72_0
  - perl-number-format=1.76=pl5321hd8ed1ab_0
  - perl-params-validate=1.31=pl5321hec16e2b_0
  - perl-parent=0.241=pl5321hd8ed1ab_0
  - perl-pathtools=3.75=pl5321h166bdaf_0
  - perl-readonly=2.05=pl5321ha770c72_0
  - perl-regexp-common=2017060201=pl5321hd8ed1ab_0
  - perl-scalar-list-utils=1.63=pl5321h166bdaf_0
  - perl-set-intspan=1.19=pl5321hdfd78af_2
  - perl-statistics-basic=1.6611=pl5321hdfd78af_3
  - perl-storable=3.15=pl5321hb9d3cd8_0
  - perl-svg=2.87=pl5321hd8ed1ab_0
  - perl-test-fatal=0.016=pl5321ha770c72_0
  - perl-text-format=0.62=pl5321hdfd78af_0
  - perl-time-hires=1.9764=pl5321h031d066_4
  - perl-try-tiny=0.31=pl5321ha770c72_0
  - perl-types-serialiser=1.01=pl5321hdfd78af_0
  - perl-xml-parser=2.44_01=pl5321hc3e0081_1003
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pigz=2.8=hadc24fc_1
  - piler-cr=1.06=h9948957_6
  - pillow=10.3.0=py312hdcec9eb_0
  - pip=24.2=pyh8b19718_1
  - pixman=0.43.2=h59595ed_0
  - plasmidfinder=2.1.6=py310hdfd78af_1
  - platon=1.7=pyhdfd78af_0
  - popt=1.16=1
  - prodigal=2.6.3=h7b50bb2_10
  - prompt-toolkit=3.0.43=py312h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py-cpuinfo=9.0.0=py312h06a4308_0
  - pycparser=2.22=pyh29332c3_1
  - pycurl=7.45.4=py312haf51bff_0
  - pyfastaq=3.17.0=py_2
  - pygments=2.15.1=py312h06a4308_1
  - pymummer=0.11.0=pyhdfd78af_1
  - pyparsing=3.1.4=pyhd8ed1ab_0
  - pyrodigal=3.6.3.post1=py312h0fa9677_0
  - pysam=0.22.1=py312hcfdcdd7_2
  - pysocks=1.7.1=pyha55dd90_7
  - pytables=3.10.2=py312h2895ec7_2
  - python=3.12.3=hab00c5b_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-isal=1.7.2=py312h66e93f0_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python-zlib-ng=0.5.1=py312h27ca174_0
  - python_abi=3.12=5_cp312
  - pytz=2024.1=py312h06a4308_0
  - pyyaml=6.0.2=py312h178313f_2
  - qhull=2020.2=h434a139_5
  - quast=5.3.0=py312pl5321hdcc493e_1
  - r-base=4.3.3=hf0d99cb_1
  - r-base64enc=0.1_3=r43h76d94ec_4
  - r-bslib=0.8.0=r43hc72bb7e_0
  - r-cachem=1.1.0=r43hb1dbf0f_1
  - r-cli=3.6.1=r43h884c59f_0
  - r-colorspace=2.1_0=r43h76d94ec_0
  - r-commonmark=1.9.0=r43h76d94ec_0
  - r-crayon=1.5.2=r43h6115d3f_0
  - r-digest=0.6.33=r43h884c59f_0
  - r-ellipsis=0.3.2=r43h76d94ec_0
  - r-fansi=1.0.5=r43h76d94ec_0
  - r-farver=2.1.1=r43h884c59f_0
  - r-fastmap=1.1.1=r43h884c59f_0
  - r-fontawesome=0.5.2=r43h6115d3f_0
  - r-fs=1.6.3=r43h884c59f_0
  - r-ggplot2=3.5.1=r43hc72bb7e_1
  - r-glue=1.6.2=r43h76d94ec_0
  - r-gtable=0.3.4=r43h6115d3f_0
  - r-htmltools=0.5.8.1=r43ha18555a_1
  - r-httpuv=1.6.15=r43ha18555a_1
  - r-isoband=0.2.7=r43h884c59f_0
  - r-jquerylib=0.1.4=r43h6115d3f_0
  - r-jsonlite=1.8.7=r43h76d94ec_0
  - r-labeling=0.4.3=r43h6115d3f_0
  - r-later=1.3.1=r43h884c59f_0
  - r-lattice=0.22_5=r43h76d94ec_0
  - r-lifecycle=1.0.3=r43h142f84f_0
  - r-magrittr=2.0.3=r43h76d94ec_0
  - r-mass=7.3_60=r43h76d94ec_0
  - r-matrix=1.6_1.1=r43h76d94ec_0
  - r-memoise=2.0.1=r43h6115d3f_0
  - r-mgcv=1.9_0=r43h76d94ec_0
  - r-mime=0.12=r43h76d94ec_0
  - r-munsell=0.5.0=r43h6115d3f_0
  - r-nlme=3.1_163=r43h640688f_0
  - r-pillar=1.9.0=r43h6115d3f_0
  - r-pkgconfig=2.0.3=r43h6115d3f_0
  - r-plyr=1.8.9=r43ha18555a_1
  - r-promises=1.2.1=r43h884c59f_0
  - r-r6=2.5.1=r43h6115d3f_0
  - r-rappdirs=0.3.3=r43h76d94ec_0
  - r-rcolorbrewer=1.1_3=r43h6115d3f_1
  - r-rcpp=1.0.11=r43h884c59f_0
  - r-rlang=1.1.1=r43h884c59f_0
  - r-sass=0.4.7=r43h884c59f_0
  - r-scales=1.2.1=r43h6115d3f_0
  - r-shiny=1.9.1=r43h785f33e_0
  - r-sourcetools=0.1.7_1=r43h884c59f_0
  - r-tibble=3.2.1=r43h76d94ec_0
  - r-utf8=1.2.4=r43h76d94ec_0
  - r-vctrs=0.6.4=r43h884c59f_0
  - r-viridislite=0.4.2=r43h6115d3f_0
  - r-withr=2.5.1=r43h6115d3f_0
  - r-xtable=1.8_4=r43h6115d3f_0
  - readline=8.2=h8228510_1
  - requests=2.32.3=pyhd8ed1ab_1
  - rpsbproc=0.5.0=hd6d6fdc_3
  - rsync=3.4.1=h168f954_0
  - samtools=1.21=h50ea8bc_0
  - scipy=1.15.1=py312h2809609_0
  - sed=4.8=h7b6447c_0
  - seqtk=1.4=h577a1d6_3
  - setuptools=74.1.2=pyhd8ed1ab_0
  - simplejson=3.19.3=py312h66e93f0_1
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.2.1=h8bd8927_1
  - spades=4.0.0=h6dccd9a_3
  - stack_data=0.2.0=pyhd3eb1b0_0
  - sysroot_linux-64=2.17=h0157908_18
  - tabulate=0.9.0=py312h06a4308_0
  - tar=1.34=hb2e2bae_1
  - tk=8.6.13=noxft_h4845f30_101
  - tktable=2.10=h3d55465_1
  - traitlets=5.14.3=py312h06a4308_0
  - trnascan-se=2.0.12=pl5321h7b50bb2_2
  - typing-extensions=4.12.2=py312h06a4308_0
  - typing_extensions=4.12.2=py312h06a4308_0
  - tzdata=2024a=h8827d51_1
  - urllib3=2.4.0=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wget=1.21.4=hda4d442_0
  - wheel=0.44.0=pyhd8ed1ab_0
  - widgetsnbextension=4.0.10=py312h06a4308_0
  - xopen=2.0.2=pyh707e725_2
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-inputproto=2.3.2=hb9d3cd8_1003
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.9=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h4bc722e_1
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-libxt=1.3.0=hd590300_1
  - xorg-libxtst=1.2.5=h4bc722e_0
  - xorg-recordproto=1.14.2=h7f98852_1002
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xxhash=0.8.3=hb47aa4a_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - zlib=1.3.1=hb9d3cd8_2
  - zlib-ng=2.2.4=h7955e40_0
  - zstandard=0.23.0=py312h66e93f0_2
  - zstd=1.5.7=hb8e6e7a_2
prefix: /home/genouest/cnrs_umr6553/ysevellec/.conda/envs/quast
