name: vs2
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - about-time=4.2.1=pyhd8ed1ab_1
  - alive-progress=3.0.1=pyhd8ed1ab_0
  - alsa-lib=1.2.6.1=h7f98852_0
  - amply=0.1.6=py310h06a4308_0
  - appdirs=1.4.4=pyhd8ed1ab_1
  - aragorn=1.2.41=h7b50bb2_5
  - archspec=0.2.5=pyhd8ed1ab_0
  - arrow=1.3.0=pyhd8ed1ab_1
  - attrs=24.3.0=py310h06a4308_0
  - bakta=1.11.0=pyhdfd78af_0
  - barrnap=0.9=hdfd78af_4
  - bbmap=39.09=h92535d8_0
  - bedtools=2.31.1=hf5e1c6e_2
  - binaryornot=0.4.4=pyhd3eb1b0_1
  - bio_assembly_refinement=0.5.1=py_2
  - biopython=1.84=py310hc51659f_0
  - blas=1.0=mkl
  - blast=2.16.0=h66d330f_5
  - blosc=1.21.6=he440d0b_1
  - boltons=24.1.0=py310h06a4308_0
  - bottleneck=1.4.2=py310ha9d4c09_0
  - bowtie2=2.5.4=he96a11b_6
  - brotli-python=1.1.0=py310hf71b8c6_2
  - bwa=0.7.18=he4a0461_1
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.3=hb9d3cd8_1
  - c-blosc2=2.21.3=h4cfbee9_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.18.0=h3faef2a_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=1.17.1=py310h1fdaa30_1
  - cgecore=2.0.1=pyhdfd78af_0
  - chardet=5.2.0=py310hff52083_2
  - charset-normalizer=3.4.0=pyhd8ed1ab_1
  - circlator=1.5.5=py_2
  - circos=0.69.9=hdfd78af_0
  - click=8.1.7=unix_pyh707e725_1
  - coin-or-cbc=2.10.12=h8b142ea_1
  - coin-or-cgl=0.60.9=hc46dffc_6
  - coin-or-clp=1.17.10=hc03379b_3
  - coin-or-osi=0.108.11=hf4fecb4_7
  - coin-or-utils=2.11.12=hc93afbd_6
  - coincbc=2.10.12=1_metapackage
  - conda=23.7.4=py310hff52083_0
  - conda-package-handling=1.9.0=py310h5764c6d_1
  - configargparse=1.7=pyhd8ed1ab_0
  - contourpy=1.3.1=py310hdb19cb5_0
  - cookiecutter=2.6.0=py310h06a4308_0
  - cryptography=44.0.1=py310h7825ff9_0
  - curl=8.14.1=h332b0f4_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - datrie=0.8.2=py310ha75aee5_8
  - dbus=1.13.18=hb2f20db_0
  - dfast=1.3.2=h43eeafb_0
  - diamond=2.1.10=h43eeafb_2
  - docutils=0.21.2=pyhd8ed1ab_1
  - entrez-direct=22.4=he881be0_0
  - et_xmlfile=1.1.0=py310h06a4308_0
  - expat=2.6.4=h6a678d5_0
  - fmt=10.2.1=h00ab1b0_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.55.3=py310h5eee18b_0
  - freetype=2.12.1=h267a509_2
  - gdbm=1.18=h0a1914f_2
  - gettext=0.22.5=he02047a_3
  - gettext-tools=0.22.5=he02047a_3
  - ghostx=1.3.7=h503566f_2
  - giflib=5.2.2=hd590300_0
  - git=2.49.0=pl5321h59d505e_0
  - gitdb=4.0.11=pyhd8ed1ab_1
  - gitpython=3.1.43=pyhff2d567_1
  - glib=2.84.1=h07242d1_0
  - glib-tools=2.84.1=h4833e2c_0
  - glimmerhmm=3.0.4=pl5321h503566f_9
  - gmp=6.3.0=hac33072_2
  - grapheme=0.6.0=pyhd8ed1ab_1
  - graphite2=1.3.14=hecca717_2
  - gsl=2.7=he838d99_0
  - harfbuzz=4.3.0=hf52aaf7_2
  - hdf5=1.14.0=nompi_hb72d44e_103
  - hmmer=3.4=hb6cb901_4
  - htslib=1.21=h5efdd21_0
  - icu=73.2=h59595ed_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib_resources=6.4.5=pyhd8ed1ab_1
  - infernal=1.1.5=pl5321h7b50bb2_4
  - intel-openmp=2023.0.0=h9e868ea_25371
  - isa-l=2.31.1=hb9d3cd8_1
  - jinja2=3.1.5=py310h06a4308_0
  - joblib=1.4.2=pyhd8ed1ab_1
  - jpeg=9e=h5eee18b_3
  - jsonpatch=1.33=py310h06a4308_1
  - jsonpointer=3.0.0=py310hff52083_1
  - jsonschema=4.23.0=pyhd8ed1ab_1
  - jsonschema-specifications=2024.10.1=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - k8=1.2=he8db53b_6
  - kernel-headers_linux-64=5.14.0=he073ed8_2
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.8=py310h6a678d5_0
  - kma=1.4.15=he4a0461_0
  - kraken2=2.1.3=pl5321hdcf5f25_3
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - lerc=4.0.0=h6a678d5_0
  - libaec=1.1.4=h3f801dc_0
  - libarchive=3.7.7=h75ea233_4
  - libasprintf=0.22.5=he8f35ee_3
  - libasprintf-devel=0.22.5=he8f35ee_3
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libcblas=3.9.0=12_h832b8c9_netlib
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.14.1=h332b0f4_0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=hd590300_2
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgettextpo=0.22.5=he02047a_3
  - libgettextpo-devel=0.22.5=he02047a_3
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran-ng=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libglib=2.84.1=h2ff4ddf_0
  - libgomp=15.2.0=h767d61c_7
  - libiconv=1.18=h3b78370_2
  - libidn2=2.3.7=hd590300_0
  - liblapack=3.9.0=12_hd37a5e2_netlib
  - liblapacke=3.9.0=12_hce4cc19_netlib
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libmamba=1.5.1=had39da4_2
  - libmambapy=1.5.1=py310h39ff949_2
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.28=pthreads_h94d23a6_1
  - libpng=1.6.43=h2797004_0
  - libsolv=0.7.35=h9463b59_0
  - libsqlite=3.50.4=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libxcb=1.15=h7f8727e_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.8=hfdd30dd_0
  - libzlib=1.3.1=hb9d3cd8_2
  - lz4-c=1.10.0=h5888daf_1
  - lzo=2.10=hd590300_1001
  - mamba=1.5.1=py310h51d5547_2
  - markdown-it-py=3.0.0=pyhd8ed1ab_1
  - markupsafe=3.0.2=py310h89163eb_1
  - mash=1.1=0
  - matplotlib-base=3.10.0=py310hbfdbfaf_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - metagene_annotator=1.0=h516909a_3
  - minimap2=2.28=he4a0461_3
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_2
  - mkl_fft=1.3.11=py310h5eee18b_0
  - mkl_random=1.2.8=py310h1128e8f_0
  - mob_suite=1.4.9.1=py_0
  - mpi=1.0=openmpi
  - mummer=3.23=pl5321h503566f_21
  - mummer4=4.0.1=pl5321h9948957_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncbi-amrfinderplus=4.0.19=hf69ffd2_0
  - ncbi-vdb=3.2.1=h9948957_0
  - ncurses=6.5=he02047a_1
  - numexpr=2.10.1=py310h3c60e43_0
  - numpy-base=1.26.4=py310hb5e798b_0
  - openjdk=11.0.15=hc6918da_0
  - openmpi=4.1.6=hc5af2df_101
  - openpyxl=3.1.5=py310h5eee18b_1
  - openssl=3.5.4=h26f9b46_0
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.2.3=py310h5eaa309_1
  - pbzip2=1.1.13=h1fcc475_2
  - pcre=8.45=h295c915_0
  - pcre2=10.44=hc749103_2
  - perl=5.32.1=7_hd590300_perl5
  - perl-archive-tar=2.40=pl5321hdfd78af_0
  - perl-b-cow=0.007=pl5321hd590300_0
  - perl-carp=1.38=pl5321hdfd78af_4
  - perl-clone=0.46=pl5321hec16e2b_0
  - perl-common-sense=3.75=pl5321hdfd78af_0
  - perl-compress-raw-bzip2=2.201=pl5321h87f3376_1
  - perl-compress-raw-zlib=2.105=pl5321h87f3376_0
  - perl-config-general=2.67=pl5321hdfd78af_0
  - perl-digest-perl-md5=1.9=pl5321hdfd78af_2
  - perl-encode=3.19=pl5321hec16e2b_1
  - perl-exporter=5.72=pl5321hdfd78af_2
  - perl-exporter-tiny=1.002002=pl5321hdfd78af_0
  - perl-extutils-makemaker=7.70=pl5321hd8ed1ab_0
  - perl-font-ttf=1.06=pl5321hdfd78af_1
  - perl-gd=2.83=pl5321hc25ab4d_0
  - perl-inc-latest=0.500=pl5321ha770c72_0
  - perl-io-compress=2.201=pl5321h503566f_4
  - perl-io-string=1.08=pl5321hdfd78af_4
  - perl-io-zlib=1.14=pl5321hdfd78af_0
  - perl-json=4.10=pl5321hdfd78af_1
  - perl-json-xs=4.03=pl5321h9948957_4
  - perl-list-moreutils=0.430=pl5321hdfd78af_0
  - perl-list-moreutils-xs=0.430=pl5321h7b50bb2_4
  - perl-math-bezier=0.01=pl5321hdfd78af_2
  - perl-math-round=0.07=pl5321hdfd78af_2
  - perl-math-vecstat=0.08=pl5321hdfd78af_2
  - perl-module-build=0.4232=pl5321ha770c72_0
  - perl-module-implementation=0.09=pl5321hdfd78af_3
  - perl-module-runtime=0.016=pl5321hdfd78af_2
  - perl-number-format=1.76=pl5321hdfd78af_0
  - perl-params-validate=1.31=pl5321h7b50bb2_3
  - perl-parent=0.236=pl5321hdfd78af_2
  - perl-pathtools=3.75=pl5321hec16e2b_3
  - perl-readonly=2.05=pl5321hdfd78af_1
  - perl-regexp-common=2017060201=pl5321hdfd78af_1
  - perl-scalar-list-utils=1.62=pl5321hec16e2b_1
  - perl-set-intspan=1.19=pl5321hdfd78af_2
  - perl-statistics-basic=1.6611=pl5321hdfd78af_3
  - perl-svg=2.87=pl5321hdfd78af_0
  - perl-test-fatal=0.016=pl5321hdfd78af_0
  - perl-test-nowarnings=1.06=pl5321hdfd78af_0
  - perl-text-format=0.62=pl5321hdfd78af_0
  - perl-time-hires=1.9764=pl5321h7b50bb2_6
  - perl-try-tiny=0.31=pl5321hdfd78af_1
  - perl-types-serialiser=1.01=pl5321hdfd78af_0
  - perl-xml-parser=2.44_01=pl5321hc3e0081_1003
  - pigz=2.8=h2797004_0
  - piler-cr=1.06=h9948957_6
  - pillow=11.1.0=py310hac6e08b_1
  - pip=25.0=py310h06a4308_0
  - pixman=0.46.4=h54a6638_1
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_2
  - plasmidfinder=2.1.6=py310hdfd78af_1
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - platon=1.7=pyhdfd78af_0
  - pluggy=1.5.0=pyhd8ed1ab_1
  - popt=1.16=1
  - prodigal=2.6.3=h031d066_9
  - psutil=6.1.0=py310ha75aee5_0
  - pulp=2.7.0=py310hff52083_1
  - py-cpuinfo=9.0.0=py310h06a4308_0
  - pybind11-abi=4=hd8ed1ab_3
  - pycirclize=1.9.1=pyhd8ed1ab_0
  - pycosat=0.6.6=py310h5eee18b_2
  - pycparser=2.22=pyh29332c3_1
  - pycurl=7.45.4=py310haf51bff_0
  - pyfastaq=3.17.0=py_2
  - pygments=2.18.0=pyhd8ed1ab_1
  - pyhmmer=0.11.0=py310h1fe012e_1
  - pymummer=0.11.0=pyhdfd78af_1
  - pyopenssl=24.3.0=pyhd8ed1ab_0
  - pyparsing=3.2.0=pyhd8ed1ab_2
  - pyrodigal=3.6.3.post1=py310h1fe012e_0
  - pysam=0.22.1=py310h804392c_2
  - pysocks=1.7.1=pyha55dd90_7
  - pytables=3.7.0=py310hde6a235_4
  - python=3.10.0=h543edf9_3_cpython
  - python-dateutil=2.9.0post0=py310h06a4308_2
  - python-fastjsonschema=2.21.1=pyhd8ed1ab_0
  - python-isal=1.7.2=py310ha75aee5_0
  - python-slugify=8.0.4=pyhd8ed1ab_1
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python-zlib-ng=1.0.0=py310hc104931_0
  - python_abi=3.10=5_cp310
  - pytz=2024.1=py310h06a4308_0
  - pyyaml=6.0.2=py310ha75aee5_1
  - quast=5.3.0=py310pl5321h5140242_1
  - ratelimiter=1.2.0=pyhd8ed1ab_1003
  - readline=8.2=h8228510_1
  - referencing=0.35.1=pyhd8ed1ab_1
  - reproc=14.2.5.post0=hb9d3cd8_0
  - reproc-cpp=14.2.5.post0=h5888daf_0
  - requests=2.32.3=py310h06a4308_1
  - rich=13.9.4=pyhd8ed1ab_1
  - rpds-py=0.22.3=py310h4aa5aa6_0
  - rpsbproc=0.5.0=hd6d6fdc_3
  - rsync=3.4.1=h81c0278_2
  - ruamel.yaml=0.16.12=py310h5764c6d_3
  - ruamel.yaml.clib=0.2.8=py310ha75aee5_1
  - ruby=3.2.2=h983345b_1
  - samtools=1.21=h50ea8bc_0
  - scipy=1.15.1=py310h5f9d8c6_0
  - seqkit=2.9.0=h9ee0642_0
  - setuptools=72.1.0=py310h06a4308_0
  - simplejson=3.19.3=py310ha75aee5_1
  - six=1.17.0=pyhd8ed1ab_0
  - smmap=5.0.0=pyhd8ed1ab_0
  - snakemake-minimal=5.26.0=py_0
  - snappy=1.2.2=h03e3b7b_0
  - spades=4.0.0=h6dccd9a_3
  - sqlite=3.50.4=hbc0de68_0
  - sysroot_linux-64=2.34=h087de78_2
  - tabulate=0.9.0=pyhd8ed1ab_2
  - tar=1.34=hb2e2bae_1
  - tbb=2021.8.0=hdb19cb5_0
  - text-unidecode=1.3=pyhd8ed1ab_2
  - tk=8.6.13=noxft_hd72426e_102
  - toolz=1.0.0=pyhd8ed1ab_1
  - toposort=1.10=pyhd8ed1ab_0
  - tqdm=4.67.1=py310h2f386ee_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - trnascan-se=2.0.12=pl5321h7b50bb2_2
  - types-python-dateutil=2.9.0.20241206=pyhd8ed1ab_0
  - typing-extensions=4.12.2=py310h06a4308_0
  - typing_extensions=4.12.2=py310h06a4308_0
  - tzdata=2025a=h04d1e81_0
  - unicodedata2=15.1.0=py310h5eee18b_1
  - urllib3=2.3.0=py310h06a4308_0
  - virsorter=2.2.4=pyhdfd78af_2
  - wget=1.21.4=hda4d442_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - wrapt=1.17.0=py310h5eee18b_0
  - xopen=2.0.2=pyh707e725_2
  - xorg-fixesproto=5.0=hb9d3cd8_1003
  - xorg-inputproto=2.3.2=hb9d3cd8_1003
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.9=h8ee46fc_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h4bc722e_1
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-libxtst=1.2.5=h4bc722e_0
  - xorg-recordproto=1.14.2=hb9d3cd8_1003
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xproto=7.0.31=hb9d3cd8_1008
  - xxhash=0.8.3=hb47aa4a_0
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaggo=1.5.10=hdfd78af_1
  - yaml=0.2.5=h7f98852_2
  - yaml-cpp=0.8.0=h6a678d5_1
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.3.1=hb9d3cd8_2
  - zlib-ng=2.2.5=hde8ca8f_0
  - zstandard=0.23.0=py310ha75aee5_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
    - numpy==1.25.0
    - plasmidhunter==1.4
    - scikit-learn==1.3.2
prefix: /home/genouest/cnrs_umr6553/ysevellec/.conda/envs/vs2
